import LegalPage from './LegalPage'

export default function Privacy() {
  return (
    <LegalPage label="LEGAL" title="Privacy Policy" updated="June 11, 2026">
      <h2>Overview</h2>
      <p>
        FitAgent is a web based AI fitness coach available at
        fitagent.jaimequezada.com. This policy explains what information
        FitAgent collects, where it goes, and the choices you have. FitAgent
        requires an account and is currently free to use through a 7 day
        trial. We do not collect payment information, we do not show
        advertising, and we do not use cross site tracking.
      </p>

      <h2>Information You Provide</h2>
      <p>When you use FitAgent, you provide the following.</p>
      <ul>
        <li>Your email address and name when you create an account</li>
        <li>
          What you share during onboarding, such as your training experience,
          goals, schedule, and available equipment
        </li>
        <li>Messages you send to your coach</li>
        <li>
          Workouts you log, including exercises, sets, weights, and how
          sessions felt
        </li>
      </ul>
      <p>
        Training details are personal information. Everything you share is
        used only to power your coaching and is never sold or shared for
        advertising.
      </p>

      <h2>What FitAgent Stores</h2>
      <p>
        Your coaching memory is kept as structured records rather than raw
        transcripts. FitAgent stores your profile, your current program, a log
        of program changes and coaching decisions, signals about how your
        training is going, your logged sessions, and summaries of your daily
        conversations. This is what lets your coach remember you between
        sessions and adapt your program over time.
      </p>

      <h2>AI Processing</h2>
      <p>
        FitAgent's coaching is generated by Anthropic's Claude models. When
        you message your coach or generate a program, your message and your
        training context are sent to a serverless endpoint we operate on
        Vercel, which forwards the request to Anthropic's Claude API. The API
        key never reaches your browser, every request requires your signed in
        session, and each account has daily usage limits enforced on our
        servers. Under Anthropic's API terms, prompts and outputs are not
        used to train their models. See{' '}
        <a href="https://www.anthropic.com/legal/privacy" target="_blank" rel="noopener noreferrer">
          Anthropic's Privacy Policy
        </a>{' '}
        for details.
      </p>

      <h2>Where Your Data Lives</h2>
      <p>
        Your data is stored in a database hosted by Supabase. Records are
        scoped to your account with row level security, and all traffic
        between your browser, our servers, and our providers is encrypted
        with HTTPS. Vercel, which hosts the app and its API, may retain short
        lived server logs for operational purposes.
      </p>

      <h2>Information We Do Not Collect</h2>
      <ul>
        <li>
          Payment details. FitAgent currently has no paid tier and never asks
          for a card.
        </li>
        <li>Your location, contacts, photos, or device files</li>
        <li>Advertising identifiers or cross site tracking data</li>
      </ul>

      <h2>Your Choices and Rights</h2>
      <p>
        You can update most of your training information by talking to your
        coach. To request a copy of your data, or to delete your account and
        everything associated with it, email{' '}
        <a href="mailto:support@jaimequezada.com">support@jaimequezada.com</a>{' '}
        and we will take care of it. If you are located in a jurisdiction
        that grants statutory privacy rights, such as the European Economic
        Area, the United Kingdom, or California, you can exercise those
        rights through the same email.
      </p>

      <h2>Children's Privacy</h2>
      <p>
        FitAgent is intended for adults. We do not knowingly collect
        information from children under 13. If you believe a child has
        provided information to FitAgent, please contact us and we will take
        appropriate steps.
      </p>

      <h2>Changes to This Policy</h2>
      <p>
        We may update this policy from time to time to reflect changes to the
        product or to clarify our practices. When we do, we will update the
        date at the top of this page.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about this policy can be sent to{' '}
        <a href="mailto:support@jaimequezada.com">support@jaimequezada.com</a>.
      </p>
    </LegalPage>
  )
}
