import LegalPage from './LegalPage'

export default function Terms() {
  return (
    <LegalPage label="LEGAL" title="Terms of Service" updated="June 11, 2026">
      <h2>Agreement</h2>
      <p>
        By creating an account or using FitAgent you agree to these Terms of
        Service and to the{' '}
        <a href="/privacy">Privacy Policy</a>. If you do not agree, do not use
        FitAgent.
      </p>

      <h2>Eligibility</h2>
      <p>You must be at least 18 years old to use FitAgent.</p>

      <h2>The Service</h2>
      <p>
        FitAgent is an AI fitness coach. It builds you a training program
        through conversation, remembers your sessions, and adapts your
        program over time. Coaching is generated by AI models and is provided
        for general fitness purposes only.
      </p>

      <h2>Not Medical Advice</h2>
      <p>
        <strong>
          FitAgent is not a medical service and its coaching is not medical
          advice.
        </strong>{' '}
        The coach is an AI system, not a licensed trainer, physician, or
        physical therapist. Always consult a qualified professional before
        starting a new training program, especially if you have an injury, a
        medical condition, or any doubt about whether an exercise is safe for
        you. You are responsible for training within your own limits. If
        something hurts, stop. Physical training carries inherent risk, and
        by using FitAgent you accept that you train at your own risk.
      </p>

      <h2>Free Trial and Membership</h2>
      <p>
        New accounts receive a 7 day free trial with full access. No payment
        method is collected. When the trial ends, access pauses. A paid
        membership is coming soon. If you want to keep training before then,
        contact{' '}
        <a href="mailto:support@jaimequezada.com">support@jaimequezada.com</a>{' '}
        to ask about an extension. Daily usage limits apply to every account
        to keep the service sustainable.
      </p>

      <h2>Your Content</h2>
      <p>
        You own the information you share with FitAgent. You grant us
        permission to store and process it solely to operate the service,
        including sending it to the AI providers described in the Privacy
        Policy. We do not sell your data.
      </p>

      <h2>AI Generated Content</h2>
      <p>
        Coaching responses are generated by AI and can be inaccurate,
        incomplete, or a poor fit for your situation. They are a starting
        point, not a guarantee. Use your own judgment, and verify anything
        that matters to your health before acting on it.
      </p>

      <h2>Acceptable Use</h2>
      <p>You agree not to do any of the following.</p>
      <ul>
        <li>Use FitAgent for any unlawful purpose</li>
        <li>
          Circumvent the free trial, daily usage limits, or any other access
          control
        </li>
        <li>
          Probe, disrupt, or attempt to gain unauthorized access to the
          service or other users' data
        </li>
        <li>Scrape the service or resell access to it</li>
      </ul>

      <h2>Service Availability and Changes</h2>
      <p>
        FitAgent is an early product. We may change, suspend, or discontinue
        any part of the service at any time, and we may update these terms as
        the product evolves. We may suspend or terminate accounts that
        violate these terms.
      </p>

      <h2>Disclaimers</h2>
      <p>
        FitAgent is provided as is and as available, without warranties of
        any kind, whether express or implied, including fitness for a
        particular purpose and uninterrupted availability.
      </p>

      <h2>Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, Jaime Quezada will not be
        liable for any indirect, incidental, special, consequential, or
        punitive damages, or for any injury or loss arising from your
        training decisions. Total liability for any claim relating to the
        service is limited to the amount you paid for FitAgent in the twelve
        months before the claim arose.
      </p>

      <h2>Governing Law</h2>
      <p>
        These terms are governed by the laws of the State of California,
        United States, without regard to its conflict of law principles. Any
        dispute arising out of these terms or the service will be resolved
        exclusively in the state or federal courts located in California, and
        you consent to the personal jurisdiction of those courts. Claims may
        be brought only in an individual capacity and not as part of a class
        or representative proceeding.
      </p>

      <h2>Changes to These Terms</h2>
      <p>
        We may update these terms from time to time. When we do, we will
        update the date at the top of this page. Continuing to use FitAgent
        after a change means you accept the updated terms.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms can be sent to{' '}
        <a href="mailto:support@jaimequezada.com">support@jaimequezada.com</a>.
      </p>
    </LegalPage>
  )
}
